name: Docker build and push.
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag - should point to latest commit.'
        required: true
        default: 'latest'

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo.
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
        
        # ACR login.
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        # Build and push image.
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/book-service:${{ github.event.inputs.tag }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/book-service:${{ github.event.inputs.tag }}
